#!/usr/bin/env python3
"""
Export MITRE ATT&CK and D3FEND vector embeddings to SQL for langchain-postgres PGVector.

Production-grade export using:
- LangChain PGVector schema (langchain_pg_collection, langchain_pg_embedding)
- COPY with FORMAT TEXT for fast bulk loading (handles embedded newlines)
- HNSW index (better than IVFFlat for RAG)
- Index creation AFTER data load (faster single-pass build)
- Transaction wrapping for atomicity

Generates: 04-mitre-vectors.sql (single file with all collections)
"""

import os
import argparse
import json
import yaml
from typing import List, Dict, Any
from neo4j import GraphDatabase
from openai import OpenAI

# Environment variables
NEO4J_URI = os.getenv("NEO4J_URI", "bolt://localhost:7687")
NEO4J_USER = os.getenv("NEO4J_USERNAME", "neo4j")
NEO4J_PASS = os.getenv("NEO4J_PASSWORD", "password")

# OpenAI configuration
EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIMENSIONS = 1536

# Cypher queries to fetch MITRE data
GET_ATTACK_TECHNIQUES_QUERY = """
MATCH (t:MitreAttackTechnique)
OPTIONAL MATCH (t)<-[:TACTIC_INCLUDES_TECHNIQUE]-(ta:MitreAttackTactic)
WITH t, COLLECT(DISTINCT {tactic_attack_id: ta.attack_id, tactic_name: ta.name}) AS tactics
RETURN {
    attack_id: t.attack_id,
    name: t.name,
    description: t.description,
    tactics: tactics
} AS attack_technique
"""

GET_ATTACK_MITIGATIONS_QUERY = """
MATCH (m:MitreAttackMitigation)
RETURN {
    attack_id: m.attack_id,
    name: m.name,
    description: m.description
} AS attack_mitigation
"""

GET_DEFEND_TECHNIQUES_QUERY = """
MATCH (t:MitreDefendTechnique)
MATCH (t)-[:SUB_TECHNIQUE_OF|ENABLES*0..]->(ta:MitreDefendTactic)
RETURN {
    defend_id: t.d3fendId,
    name: t.name,
    description: t.description,
    tactic_name: ta.name
} AS defend_technique
"""


def generate_embeddings(client: OpenAI, texts: List[str], batch_size: int = 100) -> List[List[float]]:
    """Generate embeddings for a list of texts using OpenAI API."""
    embeddings = []

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]
        print(f"  Generating embeddings for batch {i // batch_size + 1} ({len(batch)} texts)...")

        response = client.embeddings.create(
            model=EMBEDDING_MODEL,
            input=batch
        )

        for item in response.data:
            embeddings.append(item.embedding)

    return embeddings


def write_schema_header(output_file):
    """Write the LangChain PGVector schema (idempotent)."""
    output_file.write("""-- ============================================
-- MITRE Vector Embeddings for LangChain PGVector
-- Generated by mitre-frameworks module
-- ============================================
--
-- Production-grade export:
-- - LangChain PGVector schema
-- - COPY for bulk loading
-- - HNSW index (created after data load)
-- - Transaction wrapping
--

CREATE EXTENSION IF NOT EXISTS vector;

-- LangChain PGVector schema
CREATE TABLE IF NOT EXISTS langchain_pg_collection (
    uuid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR NOT NULL UNIQUE,
    cmetadata JSONB
);

CREATE TABLE IF NOT EXISTS langchain_pg_embedding (
    id VARCHAR PRIMARY KEY,
    collection_id UUID REFERENCES langchain_pg_collection(uuid) ON DELETE CASCADE,
    embedding vector(1536),
    document VARCHAR,
    cmetadata JSONB
);

""")


def pg_escape(value: str) -> str:
    """
    Escapes text for PostgreSQL COPY (FORMAT TEXT).

    Rules (order matters - backslash must be first):
    1. Backslash '\\' -> '\\\\'
    2. Newline '\\n' -> '\\n'
    3. Carriage Return '\\r' -> '\\r'
    4. Tab '\\t' -> '\\t'
    5. None/Null -> '\\N'
    """
    if value is None:
        return "\\N"
    return (str(value)
            .replace("\\", "\\\\")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t"))


def write_collection(output_file, collection_name: str, items: List[Dict], embeddings: List[List[float]], id_field: str):
    """
    Export a collection using COPY with FORMAT TEXT.

    FORMAT TEXT is superior to CSV for SQL scripts because it flattens multi-line
    content (YAML) into single-line escaped strings (\\n), preventing
    "unquoted newline" errors during import.

    Uses temp table pattern to handle collection UUID foreign key.
    """
    safe_name = collection_name.replace("-", "_")

    output_file.write(f"""
-- ============================================
-- Collection: {collection_name}
-- Items: {len(items)}
-- ============================================
BEGIN;

-- Ensure Collection Exists
INSERT INTO langchain_pg_collection (name, cmetadata)
VALUES ('{collection_name}', '{{}}'::jsonb)
ON CONFLICT (name) DO NOTHING;

-- Create temp table for bulk loading
CREATE TEMP TABLE tmp_load_{safe_name} (
    id VARCHAR,
    embedding vector(1536),
    document VARCHAR,
    cmetadata JSONB
) ON COMMIT DROP;

-- Bulk load using COPY with FORMAT TEXT
-- Columns separated by tabs, newlines escaped as \\n
COPY tmp_load_{safe_name} (id, embedding, document, cmetadata) FROM STDIN WITH (FORMAT TEXT);
""")

    for item, embedding in zip(items, embeddings):
        item_id = item[id_field]
        doc_id = f"{collection_name}:{item_id}"

        # Vector as Postgres array format: [0.1,0.2,...]
        vector_str = "[" + ",".join(str(v) for v in embedding) + "]"

        # Metadata: all fields except 'content'
        metadata = {k: v for k, v in item.items() if k != "content"}
        metadata_json = json.dumps(metadata)

        # Build tab-separated line with proper escaping
        row_parts = [
            pg_escape(doc_id),
            pg_escape(vector_str),
            pg_escape(item["content"]),  # Handles YAML newlines safely
            pg_escape(metadata_json)
        ]

        output_file.write("\t".join(row_parts) + "\n")

    output_file.write(f"""\\.

-- Move data from temp table to real table
INSERT INTO langchain_pg_embedding (id, collection_id, embedding, document, cmetadata)
SELECT
    t.id,
    c.uuid,
    t.embedding,
    t.document,
    t.cmetadata
FROM tmp_load_{safe_name} t
CROSS JOIN langchain_pg_collection c
WHERE c.name = '{collection_name}'
ON CONFLICT (id) DO UPDATE SET
    embedding = EXCLUDED.embedding,
    document = EXCLUDED.document,
    cmetadata = EXCLUDED.cmetadata;

COMMIT;
""")


def write_final_indexes(output_file):
    """Create indexes AFTER all data is loaded for optimal performance."""
    output_file.write("""
-- ============================================
-- Create Indexes (AFTER all data loaded)
-- ============================================
-- HNSW index is preferred over IVFFlat for RAG:
-- - No training step required
-- - Handles incremental updates better
-- - Generally better recall/performance trade-off

CREATE INDEX IF NOT EXISTS langchain_pg_embedding_embedding_idx
ON langchain_pg_embedding USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS langchain_pg_embedding_cmetadata_idx
ON langchain_pg_embedding USING gin (cmetadata jsonb_path_ops);

CREATE INDEX IF NOT EXISTS langchain_pg_embedding_collection_idx
ON langchain_pg_embedding (collection_id);
""")


def fetch_attack_techniques(driver) -> List[Dict]:
    """Fetch ATT&CK techniques from database."""
    print("Fetching ATT&CK techniques from database...")

    with driver.session() as session:
        result = session.run(GET_ATTACK_TECHNIQUES_QUERY)
        techniques = [dict(record["attack_technique"]) for record in result]

    print(f"  Found {len(techniques)} techniques")
    return techniques


def fetch_attack_mitigations(driver) -> List[Dict]:
    """Fetch ATT&CK mitigations from database."""
    print("Fetching ATT&CK mitigations from database...")

    with driver.session() as session:
        result = session.run(GET_ATTACK_MITIGATIONS_QUERY)
        mitigations = [dict(record["attack_mitigation"]) for record in result]

    print(f"  Found {len(mitigations)} mitigations")
    return mitigations


def fetch_defend_techniques(driver) -> List[Dict]:
    """Fetch D3FEND techniques from database."""
    print("Fetching D3FEND techniques from database...")

    with driver.session() as session:
        result = session.run(GET_DEFEND_TECHNIQUES_QUERY)
        techniques = [dict(record["defend_technique"]) for record in result]

    print(f"  Found {len(techniques)} techniques")

    # Deduplicate by defend_id (query may return duplicates due to multiple tactic paths)
    seen = set()
    unique_techniques = []
    for tech in techniques:
        if tech["defend_id"] not in seen:
            seen.add(tech["defend_id"])
            unique_techniques.append(tech)

    print(f"  After deduplication: {len(unique_techniques)} techniques")
    return unique_techniques


def prepare_items_for_embedding(items: List[Dict], id_field: str) -> List[Dict]:
    """
    Prepare items with content field for embedding.
    Content is YAML-formatted for consistency with index_mitre.
    """
    prepared = []
    for item in items:
        # Create content from key fields
        content_dict = {
            id_field: item[id_field],
            "name": item.get("name", ""),
            "description": item.get("description", ""),
        }
        content = yaml.dump(content_dict, default_flow_style=False, sort_keys=False)

        # Add content to item
        prepared_item = dict(item)
        prepared_item["content"] = content
        prepared.append(prepared_item)

    return prepared


def main():
    parser = argparse.ArgumentParser(
        description="Export MITRE ATT&CK and D3FEND embeddings to SQL for LangChain PGVector"
    )
    parser.add_argument(
        "--output-dir",
        default="./data",
        help="Output directory for SQL files"
    )
    args = parser.parse_args()

    # Check for OpenAI API key
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        print("Error: OPENAI_API_KEY environment variable is required")
        return 1

    # Create output directory
    os.makedirs(args.output_dir, exist_ok=True)

    # Initialize clients
    print(f"Connecting to {NEO4J_URI}...")
    driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASS))
    client = OpenAI(api_key=api_key)

    try:
        # Fetch all data
        attack_techniques = fetch_attack_techniques(driver)
        attack_mitigations = fetch_attack_mitigations(driver)
        defend_techniques = fetch_defend_techniques(driver)

        # Prepare items with content field
        print("\nPreparing items for embedding...")
        attack_tech_items = prepare_items_for_embedding(attack_techniques, "attack_id")
        attack_mit_items = prepare_items_for_embedding(attack_mitigations, "attack_id")
        defend_tech_items = prepare_items_for_embedding(defend_techniques, "defend_id")

        # Generate embeddings for all collections
        print("\nGenerating ATT&CK technique embeddings...")
        attack_tech_embeddings = generate_embeddings(client, [item["content"] for item in attack_tech_items])

        print("\nGenerating ATT&CK mitigation embeddings...")
        attack_mit_embeddings = generate_embeddings(client, [item["content"] for item in attack_mit_items])

        print("\nGenerating D3FEND technique embeddings...")
        defend_tech_embeddings = generate_embeddings(client, [item["content"] for item in defend_tech_items])

        # Write single output file
        output_path = os.path.join(args.output_dir, "04-mitre-vectors.sql")
        print(f"\nWriting {output_path}...")

        with open(output_path, "w") as f:
            # Schema header
            write_schema_header(f)

            # Export each collection
            write_collection(f, "mitre_attack_techniques", attack_tech_items, attack_tech_embeddings, "attack_id")
            write_collection(f, "mitre_attack_mitigations", attack_mit_items, attack_mit_embeddings, "attack_id")
            write_collection(f, "mitre_defend_techniques", defend_tech_items, defend_tech_embeddings, "defend_id")

            # Create indexes LAST for optimal performance
            write_final_indexes(f)

        print("\n=== Export Complete ===")
        print(f"  ATT&CK techniques: {len(attack_tech_items)}")
        print(f"  ATT&CK mitigations: {len(attack_mit_items)}")
        print(f"  D3FEND techniques: {len(defend_tech_items)}")
        print(f"  Total embeddings: {len(attack_tech_items) + len(attack_mit_items) + len(defend_tech_items)}")
        print(f"  Output: {output_path}")

    finally:
        driver.close()

    return 0


if __name__ == "__main__":
    exit(main())
