/**
 * Package the dethernety module for the module package system.
 *
 * Creates:
 * - dist/package/ directory with the module structure
 * - dist/dethernety-1.0.0.tar.gz archive
 */

import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const distDir = path.join(projectRoot, 'dist');
const packageDir = path.join(distDir, 'package');

// Read manifest for version
const manifest = JSON.parse(fs.readFileSync(path.join(projectRoot, 'manifest.json'), 'utf8'));
const { name, version } = manifest;

console.log(`Packaging ${name} v${version}...`);

// Clean and create package directory
if (fs.existsSync(packageDir)) {
  fs.rmSync(packageDir, { recursive: true });
}
fs.mkdirSync(packageDir, { recursive: true });

// 1. Copy manifest.json
console.log('  Copying manifest.json...');
fs.copyFileSync(
  path.join(projectRoot, 'manifest.json'),
  path.join(packageDir, 'manifest.json')
);

// 2. Copy compiled JavaScript (dethernety/dethernety-module/)
console.log('  Copying compiled JavaScript...');
const jsSourceDir = path.join(distDir, 'dethernety', 'dethernety-module');
const jsDestDir = path.join(packageDir, 'dethernety', 'dethernety-module');
fs.mkdirSync(jsDestDir, { recursive: true });

// Copy all .js and .d.ts files
const jsFiles = fs.readdirSync(jsSourceDir).filter(f => f.endsWith('.js') || f.endsWith('.d.ts'));
for (const file of jsFiles) {
  fs.copyFileSync(path.join(jsSourceDir, file), path.join(jsDestDir, file));
}

// 3. Copy data files (CSV and Cypher) from data/
// These are generated by the export script: pnpm export
console.log('  Copying data files...');
const dataDestDir = path.join(packageDir, 'data');
fs.mkdirSync(dataDestDir, { recursive: true });

const dataSourceDir = path.join(projectRoot, 'data');
if (fs.existsSync(dataSourceDir)) {
  const dataFiles = fs.readdirSync(dataSourceDir).filter(f =>
    f.endsWith('.csv') || f.endsWith('.cypher')
  );
  for (const file of dataFiles) {
    fs.copyFileSync(path.join(dataSourceDir, file), path.join(dataDestDir, file));
  }
  console.log(`    Copied ${dataFiles.length} data files`);
} else {
  console.warn('  WARNING: data/ not found. Run "pnpm export" first to generate data files.');
}

// 4. Create tar.gz archive
console.log('  Creating tar.gz archive...');
const archiveName = `${name}-${version}.tar.gz`;
const archivePath = path.join(distDir, archiveName);

// Use tar command to create the archive
execSync(`tar -czf "${archivePath}" -C "${packageDir}" .`);

// Summary
console.log('');
console.log('Package created successfully!');
console.log(`  Archive: ${archivePath}`);
console.log(`  Size: ${(fs.statSync(archivePath).size / 1024).toFixed(1)} KB`);
console.log('');
console.log('Package contents:');
const contents = execSync(`tar -tzf "${archivePath}"`, { encoding: 'utf8' });
console.log(contents);
