version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    ignore:
      # Memgraph only supports @neo4j/graphql 7.2.0
      # https://memgraph.com/docs/client-libraries/graphql
      - dependency-name: "@neo4j/graphql"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "docker"
    commit-message:
      prefix: "docker"
