/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisDialog: typeof import('./components/Dialogs/Analysis/AnalysisDialog.vue')['default']
    AnalysisFlowDialog: typeof import('./components/Dialogs/Analysis/AnalysisFlowDialog.vue')['default']
    AttackMitigationDialog: typeof import('./components/Dialogs/Mitre/AttackMitigationDialog.vue')['default']
    AttackTechniqueDialog: typeof import('./components/Dialogs/Mitre/AttackTechniqueDialog.vue')['default']
    AttributesDialog: typeof import('./components/DataFlow/AttributesDialog.vue')['default']
    AttributesForm: typeof import('./components/DataFlow/AttributesForm.vue')['default']
    BoundaryNode: typeof import('./components/DataFlow/Nodes/BoundaryNode.vue')['default']
    ClassConfigDialog: typeof import('./components/Dialogs/Control/ClassConfigDialog.vue')['default']
    ConfirmClassCreationDialog: typeof import('./components/Dialogs/General/ConfirmClassCreationDialog.vue')['default']
    ConfirmClassOrModelChangeDialog: typeof import('./components/Dialogs/DataFlow/ConfirmClassOrModelChangeDialog.vue')['default']
    ConfirmDeleteDialog: typeof import('./components/Dialogs/General/ConfirmDeleteDialog.vue')['default']
    ConfirmDeleteModelDialog: typeof import('./components/Dialogs/Model/ConfirmDeleteModelDialog.vue')['default']
    ContentSelectDialog: typeof import('./components/Dialogs/Browser/ContentSelectDialog.vue')['default']
    ControlDialog: typeof import('./components/Dialogs/Control/ControlDialog.vue')['default']
    CounterMeasureDialog: typeof import('./components/Dialogs/Control/CounterMeasureDialog.vue')['default']
    CustomCategorizationRenderer: typeof import('./components/DataFlow/CustomCategorizationRenderer.vue')['default']
    DataDialog: typeof import('./components/Dialogs/DataFlow/DataDialog.vue')['default']
    DataFlow: typeof import('./components/DataFlow/DataFlow.vue')['default']
    DataFlowBackground: typeof import('./components/DataFlow/DataFlowBackground.vue')['default']
    DataFlowEdge: typeof import('./components/DataFlow/Nodes/DataFlowEdge.vue')['default']
    DefendTechniqueDialog: typeof import('./components/Dialogs/Mitre/DefendTechniqueDialog.vue')['default']
    ExportModelDialog: typeof import('./components/Dialogs/Model/ExportModelDialog.vue')['default']
    ExposureDialog: typeof import('./components/Dialogs/DataFlow/ExposureDialog.vue')['default']
    ExtEntNode: typeof import('./components/DataFlow/Nodes/ExtEntNode.vue')['default']
    FolderDialog: typeof import('./components/Dialogs/Browser/FolderDialog.vue')['default']
    FolderSelectDialog: typeof import('./components/Dialogs/Browser/FolderSelectDialog.vue')['default']
    ImportModelDialog: typeof import('./components/Dialogs/Model/ImportModelDialog.vue')['default']
    IssueCard: typeof import('./components/Dialogs/Issues/IssueCard.vue')['default']
    IssueDialog: typeof import('./components/Dialogs/Issues/IssueDialog.vue')['default']
    IssueSelector: typeof import('./components/Dialogs/General/IssueSelector.vue')['default']
    ModelDialog: typeof import('./components/Dialogs/Model/ModelDialog.vue')['default']
    ModuleCard: typeof import('./components/Dialogs/Module/ModuleCard.vue')['default']
    PaletteWindow: typeof import('./components/DataFlow/PaletteWindow.vue')['default']
    ProcessNode: typeof import('./components/DataFlow/Nodes/ProcessNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsControlsTab: typeof import('./components/DataFlow/SettingsTabs/SettingsControlsTab.vue')['default']
    SettingsDataTab: typeof import('./components/DataFlow/SettingsTabs/SettingsDataTab.vue')['default']
    SettingsExposuresTab: typeof import('./components/DataFlow/SettingsTabs/SettingsExposuresTab.vue')['default']
    SettingsGeneralTab: typeof import('./components/DataFlow/SettingsTabs/SettingsGeneralTab.vue')['default']
    SettingsWindow: typeof import('./components/DataFlow/SettingsWindow.vue')['default']
    StoreNode: typeof import('./components/DataFlow/Nodes/StoreNode.vue')['default']
    UserQuestionDialog: typeof import('./components/Dialogs/Analysis/UserQuestionDialog.vue')['default']
  }
}
