name: CLA

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  cla-check:
    if: >-
      github.event_name == 'pull_request_target' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, 'recheck'))
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: CLA Assistant
        uses: contributor-assistant/github-action@v2.6.1
        with:
          path-to-signatures: signatures/cla.json
          path-to-document: CLA.md
          branch: main
          allowlist: dependabot[bot],github-actions[bot]
