name: Docker Build

on:
  pull_request:
    paths:
      - "Dockerfile.production"
      - "apps/**"
      - "packages/**"
      - "modules/**"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f Dockerfile.production -t dethernety:test .
